spring:
  profiles:
    active: usage_message
  
  datasource: 
    platform: postgres
    url: "jdbc:postgresql://postgres:5432/postgres"
    username: "postgres"
    password: "test1234"
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      # ddl-auto: update
      ddl-auto: create-drop

# server port
server:
  port: 8081

twilio:
    account_sid: ""
    auth_token: ""